/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package se_project;
import java.sql.*; 
import java.awt.Color;
import java.awt.Toolkit;
import java.awt.Dimension;
import java.sql.DriverManager;
import java.util.regex.Matcher; 
import java.util.regex.Pattern; 
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class AddNewLogin extends javax.swing.JFrame {

       Connection conn = null;
PreparedStatement stmt = null;
    public AddNewLogin() {
        initComponents();
        //next two lines will show the frame in center of screen
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2,dim.height/2-this.getSize().height/2);
        
        this.setBackground(new Color(0,0,0,0));
        jPanel1.setBackground(new Color(0,0,0,0));
        
    }
    
    public static boolean isValid(String email) 
    { 
        String emailRegex = "^[a-zA-Z0-9_+&*-]+(?:\\."+ 
                            "[a-zA-Z0-9_+&*-]+)*@" + 
                            "(?:[a-zA-Z0-9-]+\\.)+[a-z" + 
                            "A-Z]{2,7}$"; 
                              
        Pattern pat = Pattern.compile(emailRegex); 
        if (email == null) 
            return false; 
        return pat.matcher(email).matches(); 
    } 
    public static boolean isValidNumber(String phone) 
    { 
        String phoneRegex = "(0/91)?[7-9][0-9]{9}"; 
                              
        Pattern pat = Pattern.compile(phoneRegex); 
        if (phone == null) 
            return false; 
        return pat.matcher(phone).matches(); 
    } 
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        aemail = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel16 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        aphone = new javax.swing.JTextField();
        aname = new javax.swing.JTextField();
        ausername = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        apassword = new javax.swing.JPasswordField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 0, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Sign Up");
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 520, 70, 30));

        jLabel9.setBackground(new java.awt.Color(0, 153, 204));
        jLabel9.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_close_window_48px.png"))); // NOI18N
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 30, 30, 30));

        jLabel10.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Email");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 330, 160, 30));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("AUTHORITY SIGN UP");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 60, 290, 30));

        aemail.setBackground(new java.awt.Color(51, 37, 78));
        aemail.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        aemail.setForeground(new java.awt.Color(153, 153, 153));
        aemail.setText("abc@gmail.com");
        aemail.setBorder(null);
        aemail.setCaretColor(new java.awt.Color(153, 153, 153));
        aemail.setOpaque(false);
        aemail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                aemailFocusGained(evt);
            }
        });
        aemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aemailActionPerformed(evt);
            }
        });
        jPanel1.add(aemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 360, 280, 30));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 390, 280, 10));

        jLabel16.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Contact");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 400, 160, 30));

        jLabel11.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Username");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 190, 160, 30));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/SmartBinConcept1.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 400, 330));

        jLabel18.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Name");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 110, 160, 30));

        aphone.setBackground(new java.awt.Color(51, 37, 78));
        aphone.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        aphone.setForeground(new java.awt.Color(153, 153, 153));
        aphone.setText("Enter Phone no.");
        aphone.setBorder(null);
        aphone.setCaretColor(new java.awt.Color(153, 153, 153));
        aphone.setOpaque(false);
        aphone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                aphoneFocusGained(evt);
            }
        });
        aphone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aphoneActionPerformed(evt);
            }
        });
        jPanel1.add(aphone, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 440, 280, 30));

        aname.setBackground(new java.awt.Color(51, 37, 78));
        aname.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        aname.setForeground(new java.awt.Color(153, 153, 153));
        aname.setText("Enter name");
        aname.setBorder(null);
        aname.setCaretColor(new java.awt.Color(153, 153, 153));
        aname.setOpaque(false);
        aname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                anameFocusGained(evt);
            }
        });
        aname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anameActionPerformed(evt);
            }
        });
        jPanel1.add(aname, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 140, 280, 30));

        ausername.setBackground(new java.awt.Color(51, 37, 78));
        ausername.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        ausername.setForeground(new java.awt.Color(153, 153, 153));
        ausername.setText("Enter username");
        ausername.setBorder(null);
        ausername.setCaretColor(new java.awt.Color(153, 153, 153));
        ausername.setOpaque(false);
        ausername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ausernameFocusGained(evt);
            }
        });
        ausername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ausernameActionPerformed(evt);
            }
        });
        jPanel1.add(ausername, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 220, 280, 30));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 170, 280, 10));

        jLabel12.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Password");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 250, 160, 30));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 250, 280, 10));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 470, 290, 10));

        apassword.setBackground(new java.awt.Color(51, 37, 78));
        apassword.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        apassword.setForeground(new java.awt.Color(153, 153, 153));
        apassword.setText("enter password");
        apassword.setBorder(null);
        apassword.setCaretColor(new java.awt.Color(153, 153, 153));
        apassword.setOpaque(false);
        apassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                apasswordFocusGained(evt);
            }
        });
        apassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apasswordActionPerformed(evt);
            }
        });
        jPanel1.add(apassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 290, 280, 30));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 320, 280, 10));
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 520, 70, 30));

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnSignUpSwitch_1.png"))); // NOI18N
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 510, 130, 50));

        jLabel1.setBackground(new java.awt.Color(255, 51, 51));
        jLabel1.setForeground(new java.awt.Color(255, 0, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/rightPanel.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 0, 510, 590));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel3.setText("SMART DUSTBIN MANAGEMENT");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 390, 30));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/leftPanelBack.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 510, 590));

        jLabel8.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Sign In");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 40, 60, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 980, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ausernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ausernameFocusGained
        // TODO add your handling code here:
        ausername.setText("");
    }//GEN-LAST:event_ausernameFocusGained

    private void apasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_apasswordFocusGained
        // TODO add your handling code here:
        apassword.setText("");
    }//GEN-LAST:event_apasswordFocusGained

    private void aemailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_aemailFocusGained
        // TODO add your handling code here:
        aemail.setText("");
    }//GEN-LAST:event_aemailFocusGained

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        
        int flag = 0;
        Person p=new Person();
         try{
            String URL = "jdbc:mysql://localhost:3306/smart_dustbin";
            String USER_NAME = "root";
            String PASSWORD = "25Sep2000@";
            String query="INSERT into authority values(?,?,?,?,?)";
            
            conn = DriverManager.getConnection(URL, USER_NAME, PASSWORD);
            
            stmt = conn.prepareStatement(query);
            stmt.setString(1,aname.getText());
              stmt.setString(2,ausername.getText());
                stmt.setString(3,apassword.getText());
             stmt.setString(4,aemail.getText());
                stmt.setString(5,aphone.getText());
                  
                 stmt.executeUpdate();
                  JOptionPane.showMessageDialog(null, "Successfully Registered -Authority Sign Up");
        }
        catch(Exception e)
        {
             JOptionPane.showMessageDialog(null, e);
        }


    }//GEN-LAST:event_jLabel7MouseClicked

    private void ausernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ausernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ausernameActionPerformed

    private void aphoneFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_aphoneFocusGained
        // TODO add your handling code here:
        aphone.setText("");
    }//GEN-LAST:event_aphoneFocusGained

    private void aphoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aphoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aphoneActionPerformed

    private void anameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_anameFocusGained
        // TODO add your handling code here:
        aname.setText("");
    }//GEN-LAST:event_anameFocusGained

    private void anameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_anameActionPerformed

    private void aemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aemailActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_aemailActionPerformed

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jLabel9MouseClicked

    private void apasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_apasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddNewLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddNewLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddNewLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddNewLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddNewLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField aemail;
    private javax.swing.JTextField aname;
    private javax.swing.JPasswordField apassword;
    private javax.swing.JTextField aphone;
    private javax.swing.JTextField ausername;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    // End of variables declaration//GEN-END:variables
}
