/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package se_project;

import javax.swing.JOptionPane;
import java.awt.Color;
import java.awt.Toolkit;
import java.awt.Dimension;
import java.util.Random;
import java.text.DateFormat;  
import java.text.SimpleDateFormat;  
import java.util.Date;  
import java.util.Calendar;  

/**
 *
 * @author HP
 */
public class dustbin_register extends javax.swing.JFrame {

    /**
     * Creates new form dustbin_register
     */
    public dustbin_register() {
        initComponents();
        
        //next two lines will show the frame in center of screen
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2,dim.height/2-this.getSize().height/2);
        
        this.setBackground(new Color(0,0,0,0));
        jPanel1.setBackground(new Color(0,0,0,0));
    }
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        vwidth = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        vheight = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        vlastdate = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        vlevel = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        vid = new javax.swing.JTextField();
        vlocation = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 0, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        vwidth.setBackground(new java.awt.Color(51, 37, 78));
        vwidth.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        vwidth.setForeground(new java.awt.Color(153, 153, 153));
        vwidth.setText("1-100");
        vwidth.setBorder(null);
        vwidth.setCaretColor(new java.awt.Color(153, 153, 153));
        vwidth.setOpaque(false);
        vwidth.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                vwidthFocusGained(evt);
            }
        });
        vwidth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vwidthActionPerformed(evt);
            }
        });
        jPanel1.add(vwidth, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 310, 90, 30));

        jLabel9.setBackground(new java.awt.Color(0, 153, 204));
        jLabel9.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_close_window_48px.png"))); // NOI18N
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 30, 30, 30));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 340, 90, 10));

        jLabel15.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Height");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 280, 60, 30));

        vheight.setBackground(new java.awt.Color(51, 37, 78));
        vheight.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        vheight.setForeground(new java.awt.Color(153, 153, 153));
        vheight.setText("1-100");
        vheight.setBorder(null);
        vheight.setCaretColor(new java.awt.Color(153, 153, 153));
        vheight.setOpaque(false);
        vheight.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                vheightFocusGained(evt);
            }
        });
        vheight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vheightActionPerformed(evt);
            }
        });
        jPanel1.add(vheight, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 310, 90, 30));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 340, 90, 10));

        jLabel14.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Width");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 280, 60, 30));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("DUSTBIN REGISTRATION");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 70, 350, 30));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("SAVE");
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 520, 70, 30));

        jLabel12.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Location");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 200, 160, 30));

        jLabel18.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Last Empty Date");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 440, 160, 30));

        jLabel16.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Level");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 360, 160, 30));

        jLabel19.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Dustbin ID");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 120, 160, 30));

        vlastdate.setBackground(new java.awt.Color(51, 37, 78));
        vlastdate.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        vlastdate.setForeground(new java.awt.Color(153, 153, 153));
        vlastdate.setText("DDMMYYYY");
        vlastdate.setBorder(null);
        vlastdate.setCaretColor(new java.awt.Color(153, 153, 153));
        vlastdate.setOpaque(false);
        vlastdate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                vlastdateFocusGained(evt);
            }
        });
        vlastdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vlastdateActionPerformed(evt);
            }
        });
        jPanel1.add(vlastdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 470, 280, 30));
        jPanel1.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 500, 280, 10));

        vlevel.setBackground(new java.awt.Color(51, 37, 78));
        vlevel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        vlevel.setForeground(new java.awt.Color(153, 153, 153));
        vlevel.setText("0");
        vlevel.setBorder(null);
        vlevel.setCaretColor(new java.awt.Color(153, 153, 153));
        vlevel.setOpaque(false);
        vlevel.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                vlevelFocusGained(evt);
            }
        });
        vlevel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vlevelActionPerformed(evt);
            }
        });
        jPanel1.add(vlevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 390, 280, 30));
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 420, 280, 10));

        vid.setBackground(new java.awt.Color(51, 37, 78));
        vid.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        vid.setForeground(new java.awt.Color(153, 153, 153));
        vid.setText("Enter ID");
        vid.setBorder(null);
        vid.setCaretColor(new java.awt.Color(153, 153, 153));
        vid.setOpaque(false);
        vid.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                vidFocusGained(evt);
            }
        });
        vid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vidActionPerformed(evt);
            }
        });
        jPanel1.add(vid, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 150, 280, 30));

        vlocation.setBackground(new java.awt.Color(51, 37, 78));
        vlocation.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        vlocation.setForeground(new java.awt.Color(153, 153, 153));
        vlocation.setText("Enter Location");
        vlocation.setBorder(null);
        vlocation.setCaretColor(new java.awt.Color(153, 153, 153));
        vlocation.setOpaque(false);
        vlocation.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                vlocationFocusGained(evt);
            }
        });
        vlocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vlocationActionPerformed(evt);
            }
        });
        jPanel1.add(vlocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 230, 280, 30));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 180, 280, 10));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 260, 280, 10));

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnSignUpSwitch.png"))); // NOI18N
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 510, 130, 50));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/rightPanel.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, 510, 590));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel3.setText("SMART DUSTBIN MANAGEMENT");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, -1, 30));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dustbinlogo.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 390, 340));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/leftPanelBack.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 510, 590));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 980, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
            
        String LOCATION = vlocation.getText();
        String ID = vid.getText();
        String WIDTH = vwidth.getText();
        String HEIGHT = vheight.getText();
        String LEVEL = vlevel.getText();
        String LASTDATE = vlastdate.getText();
        
        Random x = new Random();
        int MOISTURE = x.nextInt(100);
        
        int flag1 = 0;
        
        for (int i = 0; i < se_project.SE_Project.dustbinlist.size(); i++) { 
           if(se_project.SE_Project.dustbinlist.get(i).id.equals(ID))
           {      
                flag1 = 1;
 
           }
        } 
        if(flag1 == 1)
        {
           JOptionPane.showMessageDialog(null,"ID already exists","Invalid ID",JOptionPane.ERROR_MESSAGE);
           vid.setText("");
           
        }
        else
        {
        double WIDTH1 = Double.parseDouble(WIDTH);
        double HEIGHT1 = Double.parseDouble(HEIGHT);
        int LEVEL1 = Integer.parseInt(LEVEL);
        Dustbin d=new Dustbin();
        d.setId(ID);
        d.setLocation(LOCATION);
        d.setWidth(WIDTH1);
        d.setHeight(HEIGHT1); 
        d.setLevel(LEVEL1);
        d.setLastEmptyDate(LASTDATE);
        d.setMoisture(MOISTURE);
        se_project.SE_Project.dustbinlist.add(d);
        JOptionPane.showMessageDialog(null,"Successfully Registered !!","Dustbin Registered successfully.",JOptionPane.INFORMATION_MESSAGE);
        vlocation.setText("");
        vid.setText("");
        vwidth.setText("");
        vheight.setText("");
        vlevel.setText("");
        vlastdate.setText("");
        
        Date date = Calendar.getInstance().getTime();  
        DateFormat dateFormat = new SimpleDateFormat("yyyy-mm-dd hh:mm:ss");  
        String strDate = dateFormat.format(date);  
        se_project.SE_Project.logreport.add("Dustbin Registered ID="+ID+", Location="+LOCATION+", Timestamp="+strDate);
        dispose();
        }
    }//GEN-LAST:event_jLabel7MouseClicked

    private void vidFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_vidFocusGained
        // TODO add your handling code here:
        vid.setText("");
    }//GEN-LAST:event_vidFocusGained

    private void vidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vidActionPerformed

    private void vlocationFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_vlocationFocusGained
        // TODO add your handling code here:
        vlocation.setText("");
    }//GEN-LAST:event_vlocationFocusGained

    private void vlocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vlocationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vlocationActionPerformed

    private void vwidthFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_vwidthFocusGained
        // TODO add your handling code here:
        vwidth.setText("");
    }//GEN-LAST:event_vwidthFocusGained

    private void vwidthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vwidthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vwidthActionPerformed

    private void vheightFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_vheightFocusGained
        // TODO add your handling code here:
        vheight.setText("");
    }//GEN-LAST:event_vheightFocusGained

    private void vheightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vheightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vheightActionPerformed

    private void vlevelFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_vlevelFocusGained
        // TODO add your handling code here:
        vlevel.setText("");
    }//GEN-LAST:event_vlevelFocusGained

    private void vlevelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vlevelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vlevelActionPerformed

    private void vlastdateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_vlastdateFocusGained
        // TODO add your handling code here:
        vlastdate.setText("");
    }//GEN-LAST:event_vlastdateFocusGained

    private void vlastdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vlastdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vlastdateActionPerformed

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jLabel9MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dustbin_register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dustbin_register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dustbin_register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dustbin_register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dustbin_register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextField vheight;
    private javax.swing.JTextField vid;
    private javax.swing.JTextField vlastdate;
    private javax.swing.JTextField vlevel;
    private javax.swing.JTextField vlocation;
    private javax.swing.JTextField vwidth;
    // End of variables declaration//GEN-END:variables
}
